### ISSUE TITLE
Not compatible with purpur

### ISSUE THREAD

**Issue by kit8379** [Rosewood-Development/PlayerPoints#10]
`[14:34:41 INFO]: [PlayerPoints] Enabling PlayerPoints v2.1.9*
[14:34:41 ERROR]: Error occurred while enabling PlayerPoints v2.1.9 (Is it up to date?)
java.lang.NoClassDefFoundError: lib/PatPeter/SQLibrary/MySQL
        at org.black_ixx.playerpoints.storage.models.MySQLStorage.connect(MySQLStorage.java:276) ~[?:?]
        at org.black_ixx.playerpoints.storage.models.MySQLStorage.<init>(MySQLStorage.java:61) ~[?:?]
        at org.black_ixx.playerpoints.storage.StorageGenerator.createStorageHandlerForType(StorageGenerator.java:47) ~[?:?]
        at org.black_ixx.playerpoints.storage.StorageHandler.starting(StorageHandler.java:63) ~[?:?]
        at org.black_ixx.playerpoints.PlayerPoints.registerModule(PlayerPoints.java:126) ~[?:?]
        at org.black_ixx.playerpoints.PlayerPoints.onEnable(PlayerPoints.java:58) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1126]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1126]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1126]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1126]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:595) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:294) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1073) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1126]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: lib.PatPeter.SQLibrary.MySQL
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1126]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1126]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 16 more
[14:34:41 INFO]: [PlayerPoints] Disabling PlayerPoints v2.1.9`

**Comment by Esophose** [comment]
Please update to the latest version of the plugin. https://www.spigotmc.org/resources/playerpoints.80745/
