### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by shiqutong** [Rosewood-Development/PlayerPoints#12]
Does this plug-in need a front plug-in to use mysql?

**Comment by Esophose** [comment]
No, it works out of the box since v3.0.0 which can be found on Spigot, the latest is v3.0.2.

**Comment by shiqutong** [comment]
[14:10:36 ERROR]: [PlayerPoints] Fatal error trying to connect to database. Please make sure all your connection settings are correct and try again. Plugin has been disabled.
[14:10:36 WARN]: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
[14:10:36 WARN]:        at org.black_ixx.playerpoints.libs.rosegarden.config.RoseSetting.getBoolean(RoseSetting.java:47)
[14:10:36 WARN]:        at org.black_ixx.playerpoints.libs.rosegarden.manager.AbstractDataManager.reload(AbstractDataManager.java:25)
[14:10:36 WARN]:        at org.black_ixx.playerpoints.libs.rosegarden.RosePlugin.getManager(RosePlugin.java:208)
[14:10:36 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:10:36 WARN]:        at org.black_ixx.playerpoints.libs.rosegarden.RosePlugin.reload(RosePlugin.java:172)
[14:10:36 WARN]:        at org.black_ixx.playerpoints.PlayerPoints.reload(PlayerPoints.java:75)
[14:10:36 WARN]:        at org.black_ixx.playerpoints.libs.rosegarden.RosePlugin.onEnable(RosePlugin.java:99)
[14:10:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:10:36 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:10:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:10:36 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[14:10:36 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[14:10:36 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[14:10:36 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[14:10:36 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[14:10:36 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:10:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by shiqutong** [comment]
mysql-settings:

  # Enable MySQL
  # If false, SQLite will be used instead
  # Default: false
  enabled: MySQL

  # MySQL Database Hostname
  # Default: 
  hostname: 192.168.1.3

  # MySQL Database Port
  # Default: 3306
  port: 3306

  # MySQL Database Name
  # Default: 
  database-name: points

  # MySQL Database User Name
  # Default: A
  user-name: root

  # MySQL Database User Password
  # Default: 
  user-password: root

  # If the database connection should use SSL
  # You should enable this if your database supports SSL
  # Default: false
  use-ssl: false

**Comment by shiqutong** [comment]
Is there something wrong with my settings?

**Comment by Esophose** [comment]
You need to set enabled to true and not MySQL

**Comment by shiqutong** [comment]
Thank you。
